version: "3.0"
services:
  identidock:
    build: .
    ports:
      - "8080:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    links:
      - dnmonster

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis:3.0